## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [9]:
import numpy as np
a = np.array([[1,2,3,4.5,5.16,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
a

array([[ 1.  ,  2.  ,  3.  ,  4.5 ,  5.16,  6.  ],
       [ 7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  ],
       [13.  , 14.  , 15.  , 16.  , 17.  , 18.  ]])

Check the dimension you have created is correct (use “*.shape*”)

In [10]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [11]:
a[1,4] = 19.75
a

array([[ 1.  ,  2.  ,  3.  ,  4.5 ,  5.16,  6.  ],
       [ 7.  ,  8.  ,  9.  , 10.  , 19.75, 12.  ],
       [13.  , 14.  , 15.  , 16.  , 17.  , 18.  ]])

Extract the 2nd and the 3rd row of the array you created. 

In [12]:
a[1]

array([ 7.  ,  8.  ,  9.  , 10.  , 19.75, 12.  ])

In [13]:
a[2]

array([13., 14., 15., 16., 17., 18.])